### ISSUE TITLE
 shift = fmaxf(1.0,8.0-shift)

### ISSUE THREAD

**Issue by lxg2015** [ayanc/blpa#1]
hi, I don't understand the code in this line. when shift is bigger than 8, the quantized tensor cann't be recovered any more。so can I remove it? or what's the reason?

https://github.com/ayanc/blpa/blob/d1864577f7639e7cd7e21859642908120bd90ef8/blpa/ops/quant.cu.cc#L29

**Comment by ayanc** [comment]
The quantized tensor is f not shift. We add shift to f before clipping and quantizing it. We use the same value of shift (with the fmaxf) when reconstructing from the quantized tensor in rest_kern4. As long as we use the same value of shift in both save_kern* and rest_kern*, the tensor can be recovered. 

The only reason we add shift to f before clipping is to keep the 'clip window' centered approximately around the bias. But we need to make sure this window is such that we can distinguish between negative and positive values of the tensor, to be able to compute its sign for back-propagation through a ReLU. We can not do this if shift < 1, which is why this line is necessary.
